services:
  master:
    image: locustio/locust
    ports:
      - "8089:8089"
    volumes:
      - ./:/mnt/locust
    command: -f /mnt/locust/reserve-one.py --master -H http://host.docker.internal:8087

  worker:
    image: locustio/locust
    deploy:
      replicas: 3
    volumes:
      - ./:/mnt/locust
    command: -f /mnt/locust/reserve-one.py --worker --master-host master