services:
  inventory-mysql:
    image: mysql:8.0.29
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: testdb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - inventory-mysql-data:/var/lib/mysql
    restart: always
  classes-mysql:
    image: mysql:8.0.29
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: testdb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3308:3306"
    volumes:
      - classes-mysql-data:/var/lib/mysql
    restart: always
  reservation-mysql:
    image: mysql:8.0.29
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: testdb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3305:3306"
    volumes:
      - reservation-mysql-data:/var/lib/mysql
    restart: always
  redis:
    image: redis:7.4.0
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: always

volumes:
  inventory-mysql-data:
    driver: local
  classes-mysql-data:
    driver: local
  reservation-mysql-data:
    driver: local
  redis-data:
    driver: local