spring:
  application:
    name: play-reservation

server:
  port: 8084

---

spring:
  config:
    activate:
      on-profile: local

datasource:
  url: "jdbc:mysql://localhost:3305/testdb?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false&allowPublicKeyRetrieval=true"

logging:
  level:
    root: INFO
    sun.rmi: INFO
    javax.management.remote.rmi: INFO
    org.springframework: INFO
    com.zaxxer.hikari.pool.HikariPool: DEBUG
    org.hibernate: DEBUG
    org.apache.coyote: DEBUG

---

spring:
  config:
    activate:
      on-profile: default

aws:
  secret-manager:
    name: spring-transaction-local

---

spring:
  config:
    activate:
      on-profile: aws

aws:
  secret-manager:
    name: spring-transaction