spring:
  profiles:
    active: default

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        use_sql_comments: true
    open-in-view: off

---

spring:
  application:
    name: spring-transaction
  config:
    activate:
      on-profile: default

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        highlight_sql: true
        type: trace

logging:
  level:
    root: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE


---

spring:
  config:
    activate:
      on-profile: aws
  datasource:
    url: jdbc:mysql://localhost:3306/testdb?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false&allowPublicKeyRetrieval=true
    username: user
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 1
      maximum-pool-size: 200
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
      pool-name: HikariCP
      auto-commit: true
      allow-pool-suspension: false
      read-only: false
      register-mbeans: false
      validation-timeout: 5000
      leak-detection-threshold: 2000
logging:
  level:
    root: DEBUG
    org:
      hibernate: TRACE
      springframework:
        orm:
          jpa: TRACE
        jdbc: TRACE

---


spring:
  config:
    activate:
      on-profile: aws-test
  datasource:
    hikari:
      minimum-idle: 100
      maximum-pool-size: 300
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
      pool-name: HikariCP
      auto-commit: true
      allow-pool-suspension: false
      read-only: false
      register-mbeans: false
      validation-timeout: 5000
      leak-detection-threshold: 2000
  jpa:
    hibernate:
      ddl-auto: update

logging:
  level:
    root: ERROR