spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
    open-in-view: off

logging:
  level:
    root: INFO
    org:
      hibernate:
        SQL: DEBUG  # SQL 쿼리 출력
        type:
          descriptor:
            sql: TRACE  # SQL 파라미터까지 모두 출력

---

spring:
  config:
    activate:
      on-profile: default

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        highlight_sql: true
        type: trace

logging:
  level:
    root: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

---

spring:
  config:
    activate:
      on-profile: local

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        highlight_sql: true
        type: trace

logging:
  level:
    root: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE


---

spring:
  config:
    activate:
      on-profile: aws
logging:
  level:
    root: DEBUG
    org:
      hibernate: TRACE
      springframework:
        orm:
          jpa: TRACE
        jdbc: TRACE

---


spring:
  config:
    activate:
      on-profile: aws-test
  datasource:
    hikari:
      minimum-idle: 100
      maximum-pool-size: 300
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
      pool-name: HikariCP
      auto-commit: true
      allow-pool-suspension: false
      read-only: false
      register-mbeans: false
      validation-timeout: 5000
      leak-detection-threshold: 2000
  jpa:
    hibernate:
      ddl-auto: update

logging:
  level:
    root: ERROR